name: bip48
description: BIP-0048 "Multi-Script Hierarchy for Multi-Sig Wallets" for Dart.
version: 0.0.01
repository: https://github.com/ManyMath/bip48
license: MIT

environment:
  sdk: ^3.5.4

dependencies:

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
